spring.application.name=spring-m2l

# configuration du serveur
server.servlet.context-path=/m2l

# Configuration Datasource
spring.datasource.url = jdbc:mysql://localhost:3306/m2l?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password =

# Configuration JPA - Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# keys for JWT
# pour le décodage
rsa.public-key=classpath:jwt/public.pem
# pour l'encodage
rsa.private-key=classpath:jwt/private.pem

