spring.application.name=spring-ws-inmemory
server.servlet.context-path=/ws
spring.datasource.url = jdbc:mysql://localhost:3306/spring-ws-inmemory?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect


springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=swagger-ui.html